### ISSUE TITLE
Package Page: Add Date field for Most Recent Upload

### ISSUE THREAD

**Issue by hsparra** [Anaconda-Platform/support#10]
It would be nice to list the date of the last upload for a package on the it's "main" page (conda tab) like it is listed on the "Most Recent" packages list on the organization profile page. Currently you have to go to the "files" tab to see the date.

**Comment by stephenakearns** [comment]
Example Page: https://anaconda.org/Anaconda-Notebook/anaconda-nb-extensions

**Comment by pelson** [comment]
I just created a tool which allowed me to do this from the CLI, it would be great if I could get this information on AC. https://github.com/pelson/anaconda-list-distributions

**Comment by stephenakearns** [comment]
@Discalced51 and @mistakevin - can you take a look at this item when you have a moment?

**Comment by srossross** [comment]
![image](https://cloud.githubusercontent.com/assets/741611/14254953/d7019db6-fa46-11e5-956b-9ef48083d367.png)

@hsparra would it solve this issue to add the last upload date under "total downloads" ?

**Comment by stephenakearns** [comment]
Hi @srossross - chiming in since it's been a while, yes that would resolve the issue. I'm moving this back into the backlog since we have a lot listed as "in progress"

**Comment by koverholt** [comment]
Issue moved to [Anaconda-Platform/anaconda-server #4782](https://github.com/Anaconda-Platform/anaconda-server/issues/4782) via [**ZenHub**](https://www.zenhub.com/)
