### ISSUE TITLE
Anaconda Cloud - confusing labels interface

### ISSUE THREAD

**Issue by gbrener** [Anaconda-Platform/support#100]
Under the "Files" tab in Anaconda Cloud, labels can be added to packages via drop-down menus. The text-entry field for label creation is the same color as the default "main" label, and just says "New label...", which don't make it particularly clear that you can type into it. After clicking on the "+" sign, an error is raised about the label being blank. After 5 minutes or so I discovered the menu could be used for entering text.

We should make this field easier to notice or change the interface to make label-creation more obvious.

**Comment by koverholt** [comment]
Issue moved to [Anaconda-Platform/anaconda-server #4795](https://github.com/Anaconda-Platform/anaconda-server/issues/4795) via [**ZenHub**](https://www.zenhub.com/)
