### ISSUE TITLE
Looking for r package version 3.3.3 for linux distribution

### ISSUE THREAD

**Issue by uttamkumar123** [Anaconda-Platform/support#103]
Looking for r package version 3.3.3 for linux distribution.
I have conda version 4.3.14 installed but not able to get to r version 3.3.3.
Can anyone please suggest how can i update R on my machine.

My machine os - RHEL 6.7

**Comment by mingwandroid** [comment]
We skipped `R 3.3.3`. The latest version is `R 3.4.2` and we provide that now.

To install this version, please update via:

```
conda update conda
conda update r-essentials=1.7.0
```

@csoja, can you close this? I do not have permissions.
