### ISSUE TITLE
R Studio Console Cursor races ahead of printed character

### ISSUE THREAD

**Issue by rlphelps** [Anaconda-Platform/support#107]
The R Studio console when R is invoked from  anaconda-navigator has an issue with the console cursor. 
It races ahead of the the location where the characters are being displayed as I type commands.

My environment has python3.5 and Rstudio 1.0.136.

**Comment by mingwandroid** [comment]
You need to select a monospaced font. From `RStudio` go to `Tools=>Global Options=>Appearance=>Editor Font`.

We provide 4 different monospaces ones that you can pick from:

```
DejaVu Sans Mono
Inconsolata
Source Code Pro
Ubuntu Mono
```

**Comment by mingwandroid** [comment]
Can someone close this? I do not have permissions to do that.
