### ISSUE TITLE
Private package initially displayed as public

### ISSUE THREAD

**Issue by rmancy-smg** [Anaconda-Platform/support#108]
Hi,

I uploaded a package via the anaconda cli, and used the `--private` flag (for the first time, I've never had this package in my repo before). In the browser, and specifically on  ''Package repository for <username>" page, in the table and under the 'Access' column it was listed as 'public'. Thankfully it wasn't actually public (I verified by logging out and trying to view it). I then manually set it to private from within the browser, and only then did the UI reflect this change. I hope this is enough detail. 

Cheers.

**Comment by j0hn** [comment]
Fixed on https://github.com/Anaconda-Platform/anaconda-server/issues/4485
