### ISSUE TITLE
Uploaded package appears in activity feed but not in packages view

### ISSUE THREAD

**Issue by fuxuelei** [Anaconda-Platform/support#109]
Using anaconda upload says the package we built was uploaded successfully and the new version number appears in the activity feed. However, when we navigate to the package's page, the latest version is still tagged as the old version, and the new version does not appear to be published.

**Comment by csoja** [comment]
Is this still the case (that the package you uploaded is not tagged as the latest version)? Can you provide details of the channel/package in question?

**Comment by koverholt** [comment]
Closing as stale. In the future, bugs or enhancement requests for Anaconda Cloud can be submitted at https://www.anaconda.com/contact-us/ if this issue occurs again.
