### ISSUE TITLE
Registered an account on Cloud with username starting with a number

### ISSUE THREAD

**Issue by 4nickpick** [Anaconda-Platform/support#112]
Created an account on Cloud with the username `4nickpick` but the Cloud desktop application does not allow users to log in with usernames starting with numbers. :sad:

**Comment by 4nickpick** [comment]
The username field on Windows does not allow a number to be entered as the first character in the field. Can't make it happen with any combination of copy/paste or rearranging characters either.

**Comment by 4nickpick** [comment]
Ended up adding a secondary email address (no verification required, so it can be garbage), removing my primary email address from the account, then signing up for a new account with a username that can be used by the desktop application. Cheers.

**Comment by 030jmk** [comment]
Can confirm this issue as well on windows 10

**Comment by KanXu00** [comment]
My users name has a "." and I can't login to the Cloud on windows 7 either

**Comment by koverholt** [comment]
Issue moved to [Anaconda-Platform/anaconda-server #4799](https://github.com/Anaconda-Platform/anaconda-server/issues/4799) via [**ZenHub**](https://www.zenhub.com/)
