### ISSUE TITLE
Purpose of .continuum directory

### ISSUE THREAD

**Issue by jakirkham** [Anaconda-Platform/support#113]
_From @jakirkham on May 19, 2017 23:53_

I'm trying to understand the purpose of the `.continuum` directory. Is this something that is still needed for some purpose? If so, what is it? Also, assuming it is needed, is there a way to relocate this out of the home directory to somewhere else (perhaps `conda`'s install location)? Thanks.

_Copied from original issue: conda/conda#5389_

**Comment by jakirkham** [comment]
_From @kalefranz on May 20, 2017 19:21_

Conda does not use a `.continuum` directory at all.  To my knowledge, it never has.  Other Continuum-developed software does.  Asking on the anaconda-client tracker might be the next place to go for you...

https://github.com/Anaconda-Platform/support/issues

**Comment by koverholt** [comment]
This does not appear to be an issue with Anaconda Cloud. Issues related to Anaconda or Conda can be reported in the corresponding Github issue tracker: https://anaconda.org/contact/report.
