### ISSUE TITLE
Anaconda Navigator won't launch on Mac OS Sierra 10.12.5

### ISSUE THREAD

**Issue by klacher27** [Anaconda-Platform/support#114]
Executing sudo rm -rf ~/.continuum/
did not work.

This is the stack trace:

![screen shot 2017-05-27 at 2 45 33 pm](https://cloud.githubusercontent.com/assets/12385993/26524009/c95b1e28-42eb-11e7-9874-0b8658173956.png)

**Comment by koverholt** [comment]
This does not appear to be an issue with Anaconda Cloud. Issues related to Anaconda or Conda can be reported in the corresponding Github issue tracker: https://anaconda.org/contact/report.
