### ISSUE TITLE
Getting PyQt4 instead of PyQt5

### ISSUE THREAD

**Issue by n12ikip12ain** [Anaconda-Platform/support#116]
Hi
I am trying to get pyqt4 instead of pyqt5, which came with anaconda when i downloaded it. I have deleted all of the files from the directory that related to pyqt5 and it is still not allowing me to download pyqt4. This is the error I am getting
UnsatisfiableError: The following specifications were found to be in conflict:
  - navigator-updater -> pyqt >=5.6 -> qt 5.6.0
  - pyqt 4*
Use "conda info <package>" to see the dependencies for each package.
Thanks

**Comment by n12ikip12ain** [comment]
I solved it by creating an another environment and downloading pyqt4 there. If anyone looks at this in the future

**Comment by ccordoba12** [comment]
Ok, thanks for letting us know about it.

**Comment by csoja** [comment]
Since there sounds like there is a solution, I will close this issue.
