### ISSUE TITLE
PyPI Packages Do Not Appear in PyCharm

### ISSUE THREAD

**Issue by RGAlexander216** [Anaconda-Platform/support#122]
If you are already aware of the functionality of PyCharm let me apologize in advance for my too-detailed-explanation of how to navigate the IDE.
Platform Information:
  Windows 10
  Anaconda: 4.4
  Conda: 4.3.22
  python 3.6.1
  pip: 9.0.1
  .condarc channels:
    - defaults
    - conda-forge
    - pypi (says it doesn't exist in traceback on command line)
    - conda-canary
    - javascript

This is only a problem when using a top level python.exe from an anaconda distribution. It has been this way since early this year at least. 

In PyCharm, if you go to File>(Project/Default) Settings>Python Interpreter you will see all your current packages. If you click the green "+" in the upper right corner of this area you are able to install new packages from the IDE interface. Anaconda repo packages do appear, however, despite all efforts to add the Anaconda or PyPI URL to the repositories/channels nothing has resolved the problem.

You can also add new URLs by clicking the bottom button that says "Manage Repositories" but even adding any of the following does not resolve the issue: 
===> https://pypi.anaconda.org/pypi/simple
===> https://pypi.python.org/pypi/simple
===> https://pypi.python.org/pypi/

**Comment by csoja** [comment]
.condarc channels are supposed to be channels with conda packages - there are no conda packages on the pypi channel as packages from PyPI are installed using pip, not conda. What happens if that channel is removed from your .condarc file?  

PyCharm has done some integration with Anaconda and conda - so, this question may be better directed to PyCharm directly (the ability to conda install and pip install packages when using Anaconda).

**Comment by RGAlexander216** [comment]
Right, I will follow up with them if that turns out to be the case.

To answer your question about removing the address from the .condarc file,
it has no noticeable effect. Meaning there are no new packages that area in
PyCharm's settings for the python interpreter.

The peculiar part is that if a new subdirectory is created and a
python.exe+pythonw.exe ("python(w).exe") is placed in the subdirectory all
the pip-installable packages do appear but all of the conda packages do not
appear in PyCharm anymore. Also, if the copy the python(w).exe that was
created when installing Anaconda is deleted and replaced with a regular
(working and PyCharm compatible) version of python(w).exe the
pip-installable packages still do not appear.

The reason I decided this was the probably place to go first instead of
PyCharm's repo was because it seems fairly obvious there is some kind of
top level controller that may be (purposefully?) preventing this from
displaying both simultaneously.

Does that all make sense?

On Jun 22, 2017 10:36 AM, "csoja" <notifications@github.com> wrote:

.condarc channels are supposed to be channels with conda packages - there
are no conda packages on the pypi channel as packages from PyPI are
installed using pip, not conda. What happens if that channel is removed
from your .condarc file?

PyCharm has done some integration with Anaconda and conda - so, this
question may be better directed to PyCharm directly (the ability to conda
install and pip install packages when using Anaconda).

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Anaconda-Platform/support/issues/122#issuecomment-310417638>,
or mute the thread

**Comment by koverholt** [comment]
This does not appear to be an issue with Anaconda Cloud. Issues related to Anaconda or Conda can be reported in the corresponding Github issue tracker: https://anaconda.org/contact/report.
