### ISSUE TITLE
How do I get ipywidgets to appear in my notebooks on anaconda cloud?

### ISSUE THREAD

**Issue by ceball** [Anaconda-Platform/support#124]
I have a notebook with ipywidgets, which I saved using "Widgets > Save Notebook With Widgets". 

<img width="722" alt="screen shot 2017-07-02 at 2 39 22 pm" src="https://user-images.githubusercontent.com/1929/27770324-8627d6e0-5f34-11e7-88e3-fc906ceccb99.png">

When I upload that to anaconda.org, the widgets don't display:

<img width="1000" alt="screen shot 2017-07-02 at 2 39 51 pm" src="https://user-images.githubusercontent.com/1929/27770320-7051d60e-5f34-11e7-8aaa-edabe6d8ce96.png">

However, I can see the widgets if I display that same file via nbviewer:

<img width="688" alt="screen shot 2017-07-02 at 2 40 14 pm" src="https://user-images.githubusercontent.com/1929/27770322-7cb4a19c-5f34-11e7-8e55-0a95292d35da.png">

Any idea what I might be doing wrong?

Thanks

**Comment by ceball** [comment]
In case it helps:

```
>>> import ipywidgets
>>> ipywidgets.__version__
'6.0.0'
>>> import notebook
>>> notebook.__version__
'5.0.0'
>>> import conda
>>> conda.__version__
'4.3.22'
```

**Comment by koverholt** [comment]
Issue moved to [Anaconda-Platform/anaconda-server #4802](https://github.com/Anaconda-Platform/anaconda-server/issues/4802) via [**ZenHub**](https://www.zenhub.com/)
