### ISSUE TITLE
error: Microsoft Visual C++ 14.0 is required

### ISSUE THREAD

**Issue by zhaowei699** [Anaconda-Platform/support#125]
how to install Visual C++ 14.0

**Comment by msarahan** [comment]
Visual c++ 14 is part of visual studio 2015. Please follow Microsoft's
instructions for installing VS2015 with the native compilers.
https://www.visualstudio.com/vs/older-downloads/

**Comment by koverholt** [comment]
Closing as resolved / out of scope for Anaconda Cloud.
