### ISSUE TITLE
Issue downloading from anaconda

### ISSUE THREAD

**Issue by jakirkham** [Anaconda-Platform/support#126]
Just started encountering an error today where it seems I'm unable to download things from anaconda. In particular, am running into this issue when trying to download one particular package from `conda-forge`. Did not see this yesterday or earlier today. I don't think this is a `conda` issue as `4.3.23` was in use both when it was working earlier and now when it has stopped. The error points to something about `noarch` being missing, but I don't think that is the case. Has something about anaconda's configuration changed? Have included the relevant snippet below and a link to the log it had come from.

```
Fetching package metadata ....
WARNING: The remote server could not find the noarch directory for the
requested channel with url: https://conda.anaconda.org/conda-forge
It is possible you have given conda an invalid channel. Please double-check
your conda configuration using `conda config --show`.
If the requested url is in fact a valid conda channel, please request that the
channel administrator create `noarch/repodata.json` and associated
`noarch/repodata.json.bz2` files, even if `noarch/repodata.json` is empty.
$ mkdir noarch
$ echo '{}' > noarch/repodata.json
$ bzip2 -k noarch/repodata.json
.......
ResolvePackageNotFound: 
  - python-coveralls ==2.7.0
```

ref: https://travis-ci.org/dask-image/dask-ndmeasure/jobs/259469284#L764-L781

**Comment by abarto** [comment]
@jakirkham We had some a couple of issues today. Could you check if this is still happening? I tried with that env file locally and it worked.

**Comment by jakirkham** [comment]
Thanks for the update, @abarto. Just retried. Unfortunately it seems to still be occurring. Please let me know if there is anything else you would like me to try to help debug this.

ref: https://travis-ci.org/dask-image/dask-ndmeasure/jobs/259477923#L764-L781

**Comment by jakirkham** [comment]
FWIW I tried moving the packages out of the `main` label and back into it. That seems to have made no difference.

ref: https://travis-ci.org/dask-image/dask-ndmeasure/jobs/259561668#L765-L782

**Comment by jakirkham** [comment]
Also seeing a similar issue with `coverage` 4.0.3, but only on Python 3.6. 😕

ref: https://travis-ci.org/dask-image/dask-ndmeasure/jobs/259559795#L765-L785

**Comment by glemaitre** [comment]
There is also a thread there: https://github.com/conda/conda/issues/5761

**Comment by jakirkham** [comment]
Thanks for the reference. As noted in the OP and on that issue, I don't think the cause is `conda` as things were working fine for a while using `conda` 4.3.23, which has been out for a week. However things stopped working yesterday while anaconda.org already had known issues. Would still suspect that anaconda.org has some issues leftover from yesterday.

**Comment by glemaitre** [comment]
What is strange is that the same thing is not reproducible locally. I can install those packages on my local machine but not on Travis. In the meanwhile, Travis did not change their settings or image either.

**Comment by jakirkham** [comment]
Indeed. I'm still trying to figure out a local reproducer. Just guessing, but maybe it is a networking related issue?

**Comment by jakirkham** [comment]
Looks like this was an issue with Travis CI's IP being blocked. Appears to now be resolved.

xref: https://github.com/conda/conda/issues/5761#issuecomment-319409809
