### ISSUE TITLE
RStudio is not in a appropiate resolution on Macbooks

### ISSUE THREAD

**Issue by HenrikEckermann** [Anaconda-Platform/support#127]
All Anaconda apps work in the right display resolution on my macbook Pro 2016. But if I run RStudio  then is looks very unsharp due to wrong resolution.

**Comment by koverholt** [comment]
This does not appear to be an issue with Anaconda Cloud. Issues related to Anaconda or Conda can be reported in the corresponding Github issue tracker: https://anaconda.org/contact/report.
