### ISSUE TITLE
Unable to download packages from Anaconda website

### ISSUE THREAD

**Issue by jakirkham** [Anaconda-Platform/support#128]
If I go to download a package from the Anaconda website...

<img width="1552" alt="screen shot 2017-08-09 at 01 40 33" src="https://user-images.githubusercontent.com/3019665/29106587-c605e05e-7ca3-11e7-812b-d8691b404fb7.png">

...I get a rather strange looking XML document and not the file request. Any ideas as to what is going on and/or how to fix this?

**Comment by abarto** [comment]
@jakirkham are you still having the problem? Do you which file has the problem?

**Comment by jakirkham** [comment]
Thanks for looking @abarto. Retried this morning and noticed something I had missed. Apparently NoScript is blocking the download as it doesn't like the use of XSS. If I force NoScript to do an Unsafe Reload, the download proceeds without issues. Would speculate this started in the past week, but can't narrow it down much more than that. Not sure if this should be chalked up to NoScript being overly cautious or if there is an issue worth investigating here. Feel free to close if there is not.

**Comment by abarto** [comment]
I just tried downloading a file with NoScript enabled and I got the XML you mentioned. It should work just fine if you do an Unsafe Reload right away, otherwise the token expires and you get a different error.
