### ISSUE TITLE
Linking/login with GitHub account

### ISSUE THREAD

**Issue by jakirkham** [Anaconda-Platform/support#129]
One feature that would be incredibly handy would be to allow GitHub accounts to be linked to (or even used for logging into) Anaconda. Beyond being an easy way to login, this would be a great way to manage permissions to relevant packages (e.g. providing select users with permission to a package of interest). Also it might be possible to use GitHub generated keys for uploading packages.

**Comment by jakirkham** [comment]
Related to this, it would be good if GitHub teams could be linked to Anaconda teams somehow. This way anyone on the corresponding GitHub team would gain all the permissions that the Anaconda team makes available.

**Comment by koverholt** [comment]
Issue moved to [Anaconda-Platform/anaconda-server #4803](https://github.com/Anaconda-Platform/anaconda-server/issues/4803) via [**ZenHub**](https://www.zenhub.com/)
