### ISSUE TITLE
UnsatisfiableError

### ISSUE THREAD

**Issue by cmwilliamsjr** [Anaconda-Platform/support#131]
I was trying to install netcdf4 and I get the following error and don't know how to resolve it or what to do next.

UnsatisfiableError: The following specifications were found to be in conflict:
-fiona
-netcdf4
-pywavelets

**Comment by koverholt** [comment]
This does not appear to be an issue with Anaconda Cloud. Issues related to Anaconda or Conda can be reported in the corresponding Github issue tracker: https://anaconda.org/contact/report.
