### ISSUE TITLE
conda create menuinst_win32 errors

### ISSUE THREAD

**Issue by mgrune** [Anaconda-Platform/support#133]
I'm installing anaconda python 3, version 4.4.0 on Windows machines. The installs finishes normally. But I'm getting errors when I try to use conda to update or to create virtual environments. Package resolution completes and downloads the packages but then hangs for a long time before throwing out a load of errors like so:

`conda create -n py2 python=2.7 anaconda`

> INFO menuinst_win32:__init__(182): Menu: name: 'Anaconda${PY_VER} ${PLATFORM}', prefix: 'c:\anaconda\envs\py2', env_name: 'py2', mode: 'None', used_mode: 'system' INFO menuinst_win32:__init__(182): Menu: name: 'Anaconda${PY_VER} ${PLATFORM}', prefix: 'c:\anaconda\envs\py2', env_name: 'py2', mode: 'None', used_mode: 'system' INFO menuinst_win32:__init__(182): Menu: name: 'Anaconda${PY_VER} ${PLATFORM}', prefix: 'c:\anaconda\envs\py2', env_name: 'py2', mode: 'None', used_mode: 'system' INFO menuinst_win32:__init__(182): Menu: name: 'Anaconda${PY_VER} ${PLATFORM}', prefix: 'c:\anaconda\envs\py2', env_name: 'py2', mode: 'None', used_mode: 'system' INFO menuinst_win32:__init__(182): Menu: name: 'Anaconda${PY_VER} ${PLATFORM}', prefix: 'c:\anaconda\envs\py2', env_name: 'py2', mode: 'None', used_mode: 'system' INFO menuinst_win32:__init__(182): Menu: name: 'Anaconda${PY_VER} ${PLATFORM}', prefix: 'c:\anaconda\envs\py2', env_name: 'py2', mode: 'None', used_mode: 'system' INFO menuinst_win32:__init__(182): Menu: name: 'Anaconda${PY_VER} ${PLATFORM}', prefix: 'c:\anaconda\envs\py2', env_name: 'py2', mode: 'None', used_mode: 'system'

The environment will still have been created but this hanging and waiting is really becoming a problem. I assume this is a fairly new bug because I've been installing anaconda and using conda for quite a while and never seen this error before.

**Comment by mgrune** [comment]
Additionally I can confirm this is happening when trying to update an older version of anaconda.  The updater hangs after downloading packages for 15+ minutes.  Then starts throwing up the errors mentioned above.

**Comment by mingwandroid** [comment]
Hi @mgrune, IMHO this is a bug in conda's logging (those messages are informational only so they are not an 'error' but you should not be seeing them). Can you try `conda update conda` before trying to create your env to see if the logging bug has now been fixed?

The 15+ minutes is likely down to the fact that conda does a lot more sanity checking theses days and these checks are really slow on Windows. You can disable some of them with:

`conda config --set skip_safety_checks True`

Please let me know if these things work for you.

**Comment by mgrune** [comment]
Thanks for the suggestions.  I've tried running conda update conda after installing fresh.  This goes through normally.  When I then try to create a new environment, it's a bit quicker now but I get a ton of new errors:

> extern "Python": function Cryptography_locking_cb() called, but @ffi.def_extern(
) was not called in the current subinterpreter.  Returning 0.

The environment does seem to work, so this is a step in the right direction.  

The safety check command returns an error

> Error: Error key must be one of always_yes, add_anaconda_token, allow_other_chan
nels, always_copy, changeps1, ssl_verify, auto_update_conda, update_dependencies
, offline, channel_priority, anaconda_upload, root_dir, show_channel_urls, add_b
instar_token, allow_softlinks, channel_alias, add_pip_as_python_dependency, bins
tar_upload, use_pip, not skip_safety_checks

**Comment by mgrune** [comment]
I tried on an older version and got some other errors.

The above suggestions, using anaconda 4.4.0, made no difference.  I have tried all I can think of as well as installing a fresh Windows 7 VM just to test this.  The problem is always the same.  I also tried to update my personal copy of anaconda and I get the same issues when trying to update to the latest version.

**Comment by mingwandroid** [comment]
> and I get the same issues

by this do you mean that:
1. You see some logging that's not being filtered as it should be.
and/or:
2. Creating environments is very low?

**Comment by mgrune** [comment]
The downloading of packages happens normally.  After the last package downloads, usually the "anaconda package, it hangs for a long time.  It never shows the usual output I would expect where it installs the packages.  Instead it throws out the errors mentioned above.  This happens if you create virtual environments or if you update the base environment.  However, updating some individual packages does seem to work aka, `conda update conda` does run.

This is something which has always worked and was fine until about a month ago when I noticed this happening.  It's going to be a big problem for me as I've got around a thousand machines with anaconda, all showing the same error.  Worse still as I only just convinced the bosses to go for anaconda as a replacement for canopy..._

**Comment by mingwandroid** [comment]
I will take this step by step as it seems there's a communication issue here.

> it hangs for a long time. 

It does not hang, it is installing stuff. Conda is slow on Windows. I gave you a way to mitigate some of this. Sorry there's nothing I can suggest beyond that. If you want proof of this, use Procmon from MS to inspect what is happening during the long wait period.

> It never shows the usual output I would expect where it installs the packages. Instead it throws out the errors mentioned above

Both of these issues are the same thing. Those errors are not errors, just information for *me* (and explicitly only me) that is unfortunately not being filtered due to a bug in how conda handles Python's logging module. This mishandling of Python's logging module is also the reason you do not see the things you want to see.

> Worse still as I only just convinced the bosses to go for anaconda as a replacement for canopy

Sorry to hear you are having trouble with this but really there is nothing so far to indicate anything except general slowness and the aforementioned logging bug.

**Comment by mgrune** [comment]
Sorry, yes, it wasn't clear from my end, I did understand what you were saying about the output.  The issue is really about the extreme amount of time it's taking, which our students are complaining about.  But I can understand that this isn't easy to diagnose and I think it's just something we have to live with for now.

Let's call it closed for now anyway.  Thank you very much

**Comment by mingwandroid** [comment]
OK cheers. I want to fix the slowness, but I want to do it right, not some bodge job that'll haunt me for years to come.
