### ISSUE TITLE
Tracking download counts over time

### ISSUE THREAD

**Issue by jakirkham** [Anaconda-Platform/support#135]
Would be nice if there was a way to track how many downloads are made for a certain package over time. If this is already available, would be nice to have a pointer on how to look. Otherwise this would be a nice feature to add.

**Comment by abarto** [comment]
This is shown in the package page.
<img width="1002" alt="downloads" src="https://user-images.githubusercontent.com/5585302/31176752-4eff535a-a8ea-11e7-80f6-32b5fffc48c5.png">

**Comment by jakirkham** [comment]
Not really no. To be clear, I'm asking for a graph showing download frequency over time. Obviously this will require some sort of binning as well.

**Comment by abarto** [comment]
Got it. We'll see if it's possible.

**Comment by jakirkham** [comment]
Thanks. 

To help motivate this better, the interest is in trying to determine things like how many people are still using a version of `python` for instance. This can help inform decisions about what is still worth supporting.

**Comment by koverholt** [comment]
Issue moved to [Anaconda-Platform/anaconda-server #4806](https://github.com/Anaconda-Platform/anaconda-server/issues/4806) via [**ZenHub**](https://www.zenhub.com/)
