### ISSUE TITLE
PyCharm Repositories

### ISSUE THREAD

**Issue by mtrsteve** [Anaconda-Platform/support#136]
I am trying to install new packages from within my PyCharm IDE, however when I click 'manage repositories' in my interpretter settings, it is empty. I have tried adding new URLs, but every time I close the window, they are gone. I go back into manage repositories, and it is empty again.
PyCharm2017.2.2
Windows 7
Anaconda2 4.4.0
Python 2.7

**Comment by koverholt** [comment]
This does not appear to be an issue with Anaconda Cloud. Issues related to Anaconda or Conda can be reported in the corresponding Github issue tracker: https://anaconda.org/contact/report.
