### ISSUE TITLE
Anaconda's R (installed with RStudio) unable to connect to internet with MacOS Sierra (10.12.6)

### ISSUE THREAD

**Issue by luciansmith** [Anaconda-Platform/support#137]
When running R after upgrading my mac to 10.12.6 (Sierra), R can no longer load libraries or access anything on the internet:

    > install.packages("devtools")
    --- Please select a CRAN mirror for use in this session ---
    Warning: failed to download mirrors file (internet routines cannot be loaded); using local file '/anaconda/lib/R/doc/CRAN_mirrors.csv'
[...]

    Warning: unable to access index for repository 
    https://cran.cnr.berkeley.edu/src/contrib:

    internet routines cannot be loaded
    Warning messages:
    1: In download.file(url, destfile = f, quiet = TRUE) : 
      unable to load shared object '/anaconda/lib/R/modules//internet.so': 
     dlopen(/anaconda/lib/R/modules//internet.so, 6): Library not loaded: @rpath/libssh2.1.dylib
     Referenced from: /anaconda/lib/R/modules//internet.so
     Reason: image not found
     2: package ‘devtools’ is not available (for R version 3.4.1) 

Similarly:

    > source("https://bioconductor.org/biocLite.R")
    Error in file(filename, "r", encoding = encoding) : 
      internet routines cannot be loaded
    In addition: Warning message:
    In file(filename, "r", encoding = encoding) :
      unable to load shared object '/anaconda/lib/R/modules//internet.so':
      dlopen(/anaconda/lib/R/modules//internet.so, 6): Library not loaded: @rpath/libssh2.1.dylib
      Referenced from: /anaconda/lib/R/modules//internet.so
    Reason: image not found

This happens both when I run R from Terminal and when I run R from RStudio (though RStudio only gives me the error, not the warning, and then still fails).

This does not happen if I run /usr/local/bin/R: the downloads work fine there.

This problem persisted after uninstalling Anaconda (and R) completely (by removing /anaconda/, /Applications/anaconda/ and /Users/[me]/anaconda--apparently, I've installed this multiple times and in multiple ways in the past), and re-installing (just in /Users/[me]/anaconda/)

**Comment by mingwandroid** [comment]
I need to fix this when I get time. For now, a workaround can be found here:

https://github.com/ContinuumIO/anaconda-issues/issues/4421#issuecomment-327033866

**Comment by luciansmith** [comment]
Thank you!  The workaround works for me, too.  I'll go ahead and close this, since there's an open issue already (and apologies for not finding it).

**Comment by mingwandroid** [comment]
No problem, glad to get you going again.
