### ISSUE TITLE
Conda installs incorrect version of R package r-mvtnorm (and probably others)

### ISSUE THREAD

**Issue by razrichter** [Anaconda-Platform/support#138]
When attempting to install mvtnorm, I found that the version installed (1.0_6-r342hc5dcbd2_0) is compiled for the wrong version of R (3.4.1-r3.4.1_0 -- necessary for a different package that is not yet available for v3.4.2), and cannot be loaded.
A gist of the log from a brand-new install of conda is at [https://gist.github.com/razrichter/f96762d3b0a6400ce4b6f1f2cca45af6](https://gist.github.com/razrichter/f96762d3b0a6400ce4b6f1f2cca45af6).
I also notice in that gist that nearly every r package, including r-boot, has a build string that starts with "r342".

**Comment by mingwandroid** [comment]
R is at 3.4.2 on AD now. I guess by "not yet available for v3.4.2" you mean on `conda-forge` or `bioconda`? They are not compatible with us.

In the future I will pin the R packages so they depend on the R interpreter version but we only support the latest R at present.

**Comment by razrichter** [comment]
That's right. The limiting package is (conda-forge) r-combinat, which has a maximum version of 0.0_8-r3.4.1.

**Comment by mingwandroid** [comment]
OK, you need to use the `conda-forge` R infrastructure and not the `default` one then until we achieve binary compatibility.

**Comment by razrichter** [comment]
OK. Thanks.
