### ISSUE TITLE
broken packages interfere with status display

### ISSUE THREAD

**Issue by scottdraves** [Anaconda-Platform/support#139]
i uploaded some bad packages by mistake, packages that would never work.
isuruf marked them as broken so they won't be installed by mistake, which is good,
but [the page for our package](https://anaconda.org/conda-forge/beakerx) still shows them as available, and also has a warning about non-standard labels:

![screen shot 2017-11-16 at 4 34 21 pm](https://user-images.githubusercontent.com/963093/32917086-097bb214-caec-11e7-8fe9-7ee5a41777d5.png)

1) it sounds like "broken" is standard so the warning box should not appear in this case, and
2) the badge for win-32 with an old verison should not appear, since it is not actually available.

from https://github.com/conda-forge/beakerx-feedstock/issues/9

**Comment by abarto** [comment]
This is going to be fixed on the next Anaconda Cloud release.

**Comment by scottdraves** [comment]
cool thanks!

BeakerX.com
ScottDraves.com
twitter.com/Scott_Draves

**Comment by jakirkham** [comment]
Thanks for looking into this @abarto. Are you basically implementing it as @scottdraves proposed or do you have some other thoughts on the issue?

**Comment by abarto** [comment]
We've added "broken" as a standard label (alongside "main", "dev", "alpha" and "beta") and changed the platform query so only the latest version with the "main" label is shown.

**Comment by koverholt** [comment]
Closing as resolved in Anaconda Cloud 2.33.6. In the future, bugs or enhancement requests for Anaconda Cloud can be submitted at https://www.anaconda.com/contact-us/.

**Comment by scottdraves** [comment]
awesome thank you.  it looks great now:

![screen shot 2017-11-29 at 2 08 56 pm](https://user-images.githubusercontent.com/963093/33393973-df2a29f0-d50e-11e7-8878-5e2b7ab43655.png)
