### ISSUE TITLE
"A message has been sent to our webmaster and we will work on fixing this bug."

### ISSUE THREAD

**Issue by Juanlu001** [Anaconda-Platform/support#141]
This package appears blank:

https://anaconda.org/conda-forge/spiceypy

![](https://user-images.githubusercontent.com/316517/33124279-b88148b6-cf7c-11e7-9854-06caba30781e.png)

Might be related to this:

https://github.com/conda-forge/spiceypy-feedstock/issues/3#issuecomment-346317729

cc @AndrewAnnex

**Comment by abarto** [comment]
A fix is already in place. It'll be deployed this week.

**Comment by koverholt** [comment]
Closing as resolved in Anaconda Cloud 2.33.6.
