### ISSUE TITLE
[Settings/Storage Page] Sort by size is too naive

### ISSUE THREAD

**Issue by pelson** [Anaconda-Platform/support#20]
When visiting a page such as ```https://anaconda.org/<user>/settings/storage``` there is an option to sort by total size of all distributions for a package. This would be super useful, if the sort knew the difference between a MB and KB.

![screenshot](https://cloud.githubusercontent.com/assets/810663/12577419/1ba59172-c412-11e5-8afc-347ab3b91c86.png)

**Comment by srossross** [comment]
Thanks for reporting @pelson. 

@Discalced51 or @mistakevin  can you look into the tablesort js library?

**Comment by mistakevin** [comment]
I'll leave this here for reference: https://mottie.github.io/tablesorter/docs/example-parsers-metric.html

**Comment by stephenakearns** [comment]
Hi @dsludwig - is there a good user account with a set of packages already uploaded I could use to validate this fix in https://develop.anaconda.org?

**Comment by dsludwig** [comment]
<img width="751" alt="screen shot 2016-05-13 at 9 05 15 am" src="https://cloud.githubusercontent.com/assets/787031/15254082/d84151dc-18e9-11e6-96b7-221d49fcdaac.png">

This is fixed as of the 2.16.3 release.
