### ISSUE TITLE
Error: HTTPError: 503 Server Error: Service Unavailable: Back-end server is at capacity for url

### ISSUE THREAD

**Issue by jakirkham** [Anaconda-Platform/support#22]
Seeing this error when trying to update

```
Error: HTTPError: 503 Server Error: Service Unavailable: Back-end server is at capacity for url: https://repo.continuum.io/pkgs/pro/noarch/repodata.json.bz2: https://repo.continuum.io/pkgs/pro/noarch/
```

**Comment by jakirkham** [comment]
Appears to have gone away.

**Comment by jakirkham** [comment]
Am seeing this again with a different channel. Given that this is not a widely used channel I'm very suspicious about this.

```
Using Anaconda API: https://api.anaconda.org
Fetching package metadata ...Error: HTTPError: 503 Server Error: Service Unavailable: Back-end server is at capacity for url: https://conda.anaconda.org/nanshe/linux-64/repodata.json: https://conda.anaconda.org/nanshe/linux-64
```

**Comment by jakirkham** [comment]
While persistent through several tries, this did eventually go away. However, I'm finding this a little troubling that I have seen the same sort of issue twice. Going to leave this open for now.

**Comment by koverholt** [comment]
Closing this as a stale / transient issue. Please contact us if you continue to encounter this.
