### ISSUE TITLE
Badge for platform support

### ISSUE THREAD

**Issue by jakirkham** [Anaconda-Platform/support#27]
It would be nice to have some sort of badge to summaries what platforms are supported. In particular, it would be nice to have this so it could be embedded in Readmes for instance. ~~( https://github.com/conda-forge/conda-smithy/issues/76 )~~ ( https://github.com/conda-forge/conda-smithy/issues/79 )

**Comment by stephenakearns** [comment]
Hi @jakirkham - thanks for your submission. We'll review and prioritize.

**Comment by koverholt** [comment]
Issue moved to [Anaconda-Platform/anaconda-server #4780](https://github.com/Anaconda-Platform/anaconda-server/issues/4780) via [**ZenHub**](https://www.zenhub.com/)
