### ISSUE TITLE
Bad link on report a bug page.

### ISSUE THREAD

**Issue by flamingbear** [Anaconda-Platform/support#32]
On `https://anaconda.org/contact/report`

There is a bad link for "Using anaconda-build system." that goes to `https://github.com/Anaconda-Server/anaconda-build/issues`.

Also, Where did anaconda-build/issues go?

Thanks
Matt

**Comment by rafaelhbarros** [comment]
Where should it go?

**Comment by stephenakearns** [comment]
this was caused by making the anaconda-build repo being made private. Discussing making it public again.

**Comment by stephenakearns** [comment]
this should be resolved now - build repo was made public again.
