### ISSUE TITLE
Build fails with HTTPError: 500 Server Error 

### ISSUE THREAD

**Issue by melund** [Anaconda-Platform/support#36]
Cloud builds are failing at the moment. Are there issues with the repo servers?

``` 
Fetching package metadata: ...Error: HTTPError: 500 Server Error: Internal Server Error for url: https://repo.continuum.io/pkgs/pro/noarch/repodata.json.bz2: https://repo.continuum.io/pkgs/pro/noarch/
```
I have seen it on both circleCI, travis and anaconda.org... 

See:
https://github.com/conda-forge/prompt_toolkit-feedstock/pull/4

**Comment by stephenakearns** [comment]
@kalefranz - I think you may be looking into this with a conda fix - can you update the person who submitted the issue?

**Comment by jakirkham** [comment]
Have been seeing this a lot today. Here is an example [build]( https://travis-ci.org/conda-forge/staged-recipes/builds/160685647#L246 ) that is suffering from this issue.

**Comment by jakirkham** [comment]
Here is another [example]( https://travis-ci.org/conda-forge/staged-recipes/builds/160686730#L185 ).

**Comment by kalefranz** [comment]
These 500 errors have long been resolved.

**Comment by csoja** [comment]
@kalefranz, @jakirkham included an example from 10 days ago.  When you say "long been resolved" - I'm assuming you mean more than 10 days ago.  Any idea why he would still be seeing one?

**Comment by jakirkham** [comment]
Maybe something that would help would be to know what PR/version added this fix for `conda` to see if we are in fact using that fix or not.
