### ISSUE TITLE
Thumbnails not rendering on https://beta.anaconda.org/<user>/notebooks#

### ISSUE THREAD

**Issue by tonyfast** [Anaconda-Platform/support#38]
The PNG strings are not encoded correctly for the [thumbnails on the notebook overview](https://beta.anaconda.org/tonyfast/notebooks#).  The source of each image has `data:image/png;base64,` twice.

Below is sample of the png string.

```
"data:image/png;base64,data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAyAAAAJYCAYAAACadoJwAAAgAElEQVR4"
```

**Comment by stephenakearns** [comment]
Possibly related to anaconda-platform/anaconda-server#2135

**Comment by dsludwig** [comment]
@tonyfast looks like this is fixed! Thanks for the report.
