### ISSUE TITLE
documentation errors

### ISSUE THREAD

**Issue by rscohn2** [Anaconda-Platform/support#39]
http://conda.pydata.org/docs/commands/build/conda-metapackage.html
* edit links are dead

http://docs.anaconda.org/quickstart.html
* edit links are dead

* this:

    `conda env upload -f my-environment`
    should be:

    `conda env upload -f my-environment.yml`

**Comment by stephenakearns** [comment]
Thanks for reporting @rscohn2 - @kerrywatson1 would you or someone on your team be able to review and make adjustments?

**Comment by kerrywatson1** [comment]
Edit links are disabled due to replatform actively in progress; edits link to old public repo whereas new repo is private. 

Docs team will add ".yml" to quickstart.html.

**Comment by kerrywatson1** [comment]
Ready to review and merge, https://github.com/Anaconda-Platform/anaconda-server/pull/2233

**Comment by stephenakearns** [comment]
thanks @kerrywatson1 - can you move the PR to the "Ready for review" pipeline and the team will pick up the PR to review.

**Comment by kerrywatson1** [comment]
Verified this is live, closing.
