### ISSUE TITLE
The Notebook description does not update.

### ISSUE THREAD

**Issue by tonyfast** [Anaconda-Platform/support#40]
[In this notebook](https://beta.anaconda.org/tonyfast/numbacythonredux/notebook), I have changed the description at some point in the revision history.  The description shown on the page does not match the description in the notebook metadata data.  It is still showing the original description from the first upload.

**Comment by bollwyvl** [comment]
Yeah: had noticed that.

This is part of the baggage of treating notebooks as packages: the
"summary" populates the package, not the file (which doesn't have
metadata). This happens with both anaconda-client and nb_anacondaclient
(which partially re-implements the feature... and should be unified
eventually...)

https://github.com/Anaconda-Platform/anaconda-client/blob/develop/binstar_client/utils/notebook/uploader.py#L97
https://github.com/Anaconda-Platform/nb_anacondacloud/blob/master/nb_anacondacloud/uploader.py#L117

Looks like "force" (which nb_anacondacloud doesn't support) would destroy
the package, therefore deleting history... probably not soo good

**Comment by stephenakearns** [comment]
Possible bug in Anaconda-client upload command for notebooks where the summary isn't updated when a new version of the notebook is uploaded.

**Comment by koverholt** [comment]
Issue moved to [Anaconda-Platform/anaconda-server #4783](https://github.com/Anaconda-Platform/anaconda-server/issues/4783) via [**ZenHub**](https://www.zenhub.com/)
