### ISSUE TITLE
Possible issue with linear algebra pack used for numpy compilation

### ISSUE THREAD

**Issue by mrclary** [Anaconda-Platform/support#41]
I have recently discovered an issue with Anaconda installations of numpy >=1.9.3.
I believe it is related to the linear algebra library used to compile numpy since my MacPorts install of numpy 1.10.4 does not produce the error.
The behavior is detailed below.

With Anaconda numpy version <= 1.9.2 and all MacPorts numpy versions, polyfit behaved correctly, as follows:

    In [1]: np.polyfit([1, 10], [np.nan, np.nan], 1)
    Out[1]: array([ nan,  nan])

But for Anaconda numpy version >=1.9.3, polyfit raises the following error:

    In [1]: np.polyfit([1, 10], [np.nan, np.nan], 1)
    ---------------------------------------------------------------------------
    ValueError                                Traceback (most recent call last)
    <ipython-input-3-bf0d5d071f08> in <module>()
    ----> 1 np.polyfit([1, 10], [np.nan, np.nan], 1)
    
    /Users/rclary/anaconda/lib/python2.7/site-packages/numpy/lib/polynomial.pyc in polyfit(x, y, deg, rcond, full, w, cov)
        580     scale = NX.sqrt((lhs*lhs).sum(axis=0))
        581     lhs /= scale
    --> 582     c, resids, rank, s = lstsq(lhs, rhs, rcond)
        583     c = (c.T/scale).T  # broadcast scale coefficients
        584 
    
    /Users/rclary/anaconda/lib/python2.7/site-packages/numpy/linalg/linalg.pyc in lstsq(a, b, rcond)
       1865         work = zeros((lwork,), t)
       1866         results = lapack_routine(m, n, n_rhs, a, m, bstar, ldb, s, rcond,
    -> 1867                                  0, work, lwork, iwork, 0)
       1868     if results['info'] > 0:
       1869         raise LinAlgError('SVD did not converge in Linear Least Squares')
    
    ValueError: On entry to DGELSD parameter number 6 had an illegal value

Does anyone have any insight on this issue?

**Comment by mrclary** [comment]
I see that this is the wrong forum for this issue. Sorry.

**Comment by jakirkham** [comment]
Did you move this somewhere?

**Comment by mrclary** [comment]
I opened an issue on [anaconda-issues](https://github.com/ContinuumIO/anaconda-issues) located [here](https://github.com/ContinuumIO/anaconda-issues/issues/804)

**Comment by stephenakearns** [comment]
Hi @mrclary - thx for moving the issue. Closing this one.
