### ISSUE TITLE
Downloads badge displays 0k in case of more than 1000 downloads

### ISSUE THREAD

**Issue by kalefranz** [Anaconda-Platform/support#46]
_From @johanneskoester on June 17, 2016 11:48_

As the title says. See here:

[![Anaconda-Server Badge](https://anaconda.org/bioconda/snakemake/badges/downloads.svg)](https://anaconda.org/bioconda/snakemake)

_Copied from original issue: ContinuumIO/anaconda-issues#829_

**Comment by jakirkham** [comment]
Yep, agreed. Have seen this too. Would be nice to fix.

**Comment by stephenakearns** [comment]
duplicate of #42  - closing this one and keeping 42 open. 

cc: @kalefranz @jakirkham
