### ISSUE TITLE
Markdown `~~`/`line-through` objects are not rendered

### ISSUE THREAD

**Issue by tonyfast** [Anaconda-Platform/support#47]
The Markdown syntax `~~` should decorate the text with a line-through, but it doesn't.

https://anaconda.org/tonyfast/gensim-basic/notebook

**Comment by stephenakearns** [comment]
Hi @bollwyvl - can I get your thoughts on what's happening here?

**Comment by bollwyvl** [comment]
Yep, it appears to be an upstream issue in either `nbconvert` (or even `mistune`).

Here's that notebook on nbviewer:
https://nbviewer.jupyter.org/urls/notebooks.anaconda.org/tonyfast/gensim-basic/download

Note that it also doesn't handle it.

Just ran it through nbconvert, and also not seeing it locally.

**Comment by bollwyvl** [comment]
Ah, it looks like this has been fixed upstream (indeed, in mistune):
https://github.com/lepture/mistune/blob/b93f3f17f8ec21f99cdc2e39215aebf1a900f20a/CHANGES.rst#version-073

I've started the process over on conda-forge:
https://github.com/conda-forge/mistune-feedstock/pull/2

What's the appropriate way to run this up the flagpole on `defaults`?

**Comment by bollwyvl** [comment]
By the by, here's a preview of what it looks like through nbconvert with mistune 0.7.3:
https://cdn.rawgit.com/anonymous/432ae80853ef807d74f21d9180e32950/raw/bb0be5d310fea52b573e9fbf6abbff503b2c70de/gensim-basic.html
