### ISSUE TITLE
Running into download issues

### ISSUE THREAD

**Issue by jakirkham** [Anaconda-Platform/support#49]
Having trouble getting access to the `free` or `pro` channels. Not really sure why they are getting hit so hard on the weekend. Here are the sorts of errors I am seeing.

```
HTTPError: 500 Server Error: Internal Server Error for url: https://repo.continuum.io/pkgs/free/noarch/repodata.json.bz2: https://repo.continuum.io/pkgs/free/noarch/
```

```
HTTPError: 500 Server Error: Internal Server Error for url: https://repo.continuum.io/pkgs/pro/linux-64/repodata.json.bz2: https://repo.continuum.io/pkgs/pro/linux-64/
```

cc @pelson @ocefpaf @patricksnape

**Comment by jakirkham** [comment]
This seems to abated for the moment. Going to keep this open for now though in case this returns.

**Comment by jakirkham** [comment]
As soon as I say that, I'm running into this issue again.

**Comment by jakirkham** [comment]
This is definitely still causing problems. Occasionally an install doesn't run into this issue, but it is pretty rare ATM.

**Comment by jakirkham** [comment]
Should add that Miniconda downloads are very slow too.

**Comment by patricksnape** [comment]
Yup I've been seeing that too

**Comment by jakirkham** [comment]
I think this has improved since I opened it. Though I'm not totally sure that there still aren't issues in some cases.

**Comment by jakirkham** [comment]
While it has improved, it has not entirely stopped. It would still be great if someone could look into these download issues.

**Comment by srossross** [comment]
@kalefranz, this looks like it is coming from `https://repo.continuum.io`

**Comment by csoja** [comment]
We moved repo.continuum.io to a CDN in Fall 2016 - so I would expect that these issues would be very rare now, and as there have been no new activity on this issue since July, I am going to close it.  If there are still problems, please open a new issue on https://github.com/ContinuumIO/anaconda-issues/issues  Thank you!
