### ISSUE TITLE
Downloading packages available at an older time

### ISSUE THREAD

**Issue by jakirkham** [Anaconda-Platform/support#51]
It would be really useful if there was a way to download a set of packages only available at a particular moment in time. For instance, imagine a new package is released today that I don't want to use (for whatever reason). Instead I want to download the package before today. One strategy might be to use build numbers, but that doesn't really cut it as one begins specifying build numbers for everything in my stack. This is just to avoid some other newer package from breaking things. What would be preferable is if one could say they want the packages from yesterday or earlier somehow. I'm hoping this actually solves most of the use cases where one would otherwise delete or hotfix a broken package (though probably not all).

One way one might approach this problem is adding labels to each package by date. However, this doesn't sound like it would scale well and might not quite fit our constraints. Though this may prove to be a useful thought exercise.

cc @183amir @pelson @ocefpaf @mcg1969 @janschulz @jjhelmus

**Comment by 183amir** [comment]
I think a better option would be what @mcg1969 suggested:

> One thing we're considering is that instead of overwriting a package when a replacement is uploaded, we move the old package aside by appending its MD5 prefix to the URL. That way it is no longer available in the index, but still available for explicit request.

This way we can hotfix packages without worrying about reproducibility by md5sums.

**Comment by mcg1969** [comment]
I think both options have their place. A more direct form of @jakirkham's option would be to include timestamps in the Anaconda Cloud metadata.

**Comment by koverholt** [comment]
Issue moved to [Anaconda-Platform/anaconda-server #4786](https://github.com/Anaconda-Platform/anaconda-server/issues/4786) via [**ZenHub**](https://www.zenhub.com/)
