### ISSUE TITLE
Links to (some?) older package are broken

### ISSUE THREAD

**Issue by mwcraig** [Anaconda-Platform/support#52]
Over the last week I've been getting 404s on some packages that were uploaded to anaconda several months ago. 

An example error message is below:

```
Error: HTTPError: 404 Client Error: NOT FOUND for url: https://conda.anaconda.org/astropy/linux-64/pyregion-1.1.4-np110py27_0.tar.bz2: https://conda.anaconda.org/astropy/linux-64/pyregion-1.1.4-np110py27_0.tar.bz2
```

**That specific package has been replaced with a working version,** because it was needed for CI, but this package is still up and broken: https://anaconda.org/astropy/pyregion/1.1.4/download/osx-64/pyregion-1.1.4-np15py27_0.tar.bz2

**Comment by dsludwig** [comment]
@mwcraig, it appears that package is downloading correctly again. We did some digging, and I think we found the root cause.

Thanks for reporting, and please create a new issue if you encounter any other problems!
