### ISSUE TITLE
Missing packages for linux32

### ISSUE THREAD

**Issue by dharanidharan12** [Anaconda-Platform/support#53]
Checking conda requirements using (conda install --file conda_requirements.txt )
I am Getting the Output as below...

Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata .........
Solving package specifications: .
Error: Packages missing in current linux-32 channels:
- py_gd
- testfixtures
- regex

Unable to find these packages suitable for linux-32.
Please help to install the packages in my linux-32 channels.
Thanks!

**Comment by ChrisBarker-NOAA** [comment]
a note here -- these requiremetns are all in the NOAA-ORR-ERD channel on anaconda.org (and many in conda-forge) -- but not for Linux 32.

I've commented on it in:
https://github.com/NOAA-ORR-ERD/PyGnome/issues/19

Continuum may or may not want to include some of these in the future  if they are of general use. This list is here:

https://github.com/NOAA-ORR-ERD/PyGnome/blob/master/conda_requirements.txt

and there are recipes for all of them here:

https://github.com/NOAA-ORR-ERD/orr-conda-recipes

**Comment by koverholt** [comment]
Closing this as stale and in favor of the issue listed above (NOAA-ORR-ERD/PyGnome#19).
