### ISSUE TITLE
Open Source Anaconda Build CI

### ISSUE THREAD

**Issue by dhirschfeld** [Anaconda-Platform/support#55]
I note with some disappointment that Anaconda Build CI is [deprecated](https://www.continuum.io/blog/developer-blog/powering-down-the-anaconda-build-ci-system). This was actually a major selling point for me as we run GitHub Enterprise and can't host our code or build servers in the cloud. AppVeyor isn't an option as they have no [on-premises](http://help.appveyor.com/discussions/questions/2397-appveyor-internally-hosted) solution.

Given that there is no alternative enterprise build system for conda would Continuum consent to open sourcing Anaconda Build for the enterprise community to pick up?

**Comment by jakirkham** [comment]
:+1: (sorry on mobile)

**Comment by jakirkham** [comment]
cc @pelson @ocefpaf

**Comment by jakirkham** [comment]
@msarahan, it would be really nice to know what will happen with the code used to power this service. I can see this coming in very handy at conda-forge. Especially as we explore different build service options.

**Comment by teoliphant** [comment]
There is some discussion of open-sourcing this code and helping to jump-start a community-oriented and community-supported build capability for building publicly available conda packages.    Is there interest in this?     We would not have people who could spend a lot of time on this code and so there would have to be interest from others in the community to use and maintain it.

**Comment by dhirschfeld** [comment]
I'm in need of a simple, flexible on-premises CI solution so I'd be happy to donate some spare cycles to keeping it working, especially on Windows.

**Comment by koverholt** [comment]
Issue moved to [Anaconda-Platform/anaconda-server #4787](https://github.com/Anaconda-Platform/anaconda-server/issues/4787) via [**ZenHub**](https://www.zenhub.com/)
