### ISSUE TITLE
Error: HTTPError: 404 Client Error: NOT FOUND for url

### ISSUE THREAD

**Issue by Gabriel-p** [Anaconda-Platform/support#56]
(Issue brought over from https://github.com/conda/conda/issues/3285)

I'm getting the error:

````
Error: HTTPError: 404 Client Error: NOT FOUND for url: https://conda.anaconda.org/astropy/linux-64/astroml-0.3-py27_0.tar.bz2: https://conda.anaconda.org/astropy/linux-64/astroml-0.3-py27_0.tar.bz2
````

when attempting to install the `astroML` package via:

````
$ conda install -c astropy astroml=0.3
````

In the page https://anaconda.org/astropy/astroml the .tar.bz file is located in

    https://anaconda.org/astropy/astroml/0.3/download/linux-64/astroml-0.3-py27_0.tar.bz2

and the command is looking for

    https://conda.anaconda.org/astropy/linux-64/astroml-0.3-py27_0.tar.bz2

**Comment by sebastian-luna-valero** [comment]
Hello, 

I am having the same error with a different package:
```
CondaRuntimeError: Runtime error: RuntimeError: Runtime error: HTTPError: 404 Client Error: NOT FOUND for url: https://conda.anaconda.org/r/linux-64/r-recommended-3.2.2-r3.2.2_0.tar.bz2: https://conda.anaconda.org/r/linux-64/r-recommended-3.2.2-r3.2.2_0.tar.bz2
```

Could you please have a look?

Best regards,
Sebastian.

**Comment by dsludwig** [comment]
Hi @Gabriel-p @sebastian-luna-valero,

thanks for reporting! I took a look into it, and it appears to be resolved now. Please re-open this issue or create a new one if you encounter this error again.
