### ISSUE TITLE
after uploading mynotebook - all sections are visible except for the container which displays the notebook content from anacondausercontent.org

### ISSUE THREAD

**Issue by maggienj** [Anaconda-Platform/support#59]
Unable to connect

Firefox can’t establish a connection to the server at anacondausercontent.org.

    The site could be temporarily unavailable or too busy. Try again in a few moments.
    If you are unable to load any pages, check your computer’s network connection.
    If your computer or network is protected by a firewall or proxy, make sure that Firefox is permitted to access the Web.

**Comment by dsludwig** [comment]
@maggienj this issue should be resolved. Thanks for the report!
