### ISSUE TITLE
[r-base] Version 3.3.1 Build 2 and 3 disables cairo capability

### ISSUE THREAD

**Issue by dhuebner** [Anaconda-Platform/support#61]
Using r-base 3.3.1-3 disables the cairo capability for unknown reasons. With 3.3.1-1 all works fine.
With:
cairo                     1.12.18                       6
r-base                    3.3.1                         1

`echo "capabilities('cairo')" > cmd.txt && R CMD BATCH cmd.txt && cat cmd.txt.Rout`

returns 

```
cairo 
 TRUE 
```

After 
`conda install -c r  r-base=3.3.1=3`

`echo "capabilities('cairo')" > cmd.txt && R CMD BATCH cmd.txt && cat cmd.txt.Rout`
returns FALSE

```
> capabilities('cairo')
cairo 
FALSE 
> 
```

@mingwandroid Is that related to the change in  See #54 or just a build env problem?

**Comment by nick-youngblut** [comment]
At least for now, is there a work-around for this issue? 

With cairo broken, I have to use XQuartz to run rpy2 in Jupyter Notebooks. This wouldn't be so bad, except I get X11 device errors when trying to reconnect to the kernels and re-run some cells that use Rmagics. So each time this happens, I have to shut down Jupyter and then restart Jupyter and all of the kernels.

I tried just using r-base 3.3.1=1 instead, but the rpy2 version that's compatible with that r-base version doesn't work with iPython 5 (https://bitbucket.org/rpy2/rpy2/issues/361/rpy-line-magic-does-not-work-with-ipython).

**Comment by koverholt** [comment]
Closing this as stale / out of scope of Anaconda Cloud. Please report any issues with the Anaconda Distribution at https://github.com/continuumio/anaconda-issues/issues.
