### ISSUE TITLE
Notebooks not rendering

### ISSUE THREAD

**Issue by stephenakearns** [Anaconda-Platform/support#62]
Logged on behalf of @rafaelhbarros... 

Notebooks not rendering for some reason on a given machine: 

Example: 
https://anaconda.org/rafaelhbarros/image-similarity/notebook

Screenshot: https://uploads.intercomcdn.com/i/o/9882148/6e99d074ed81cfb4a47a5975/Screen%20Shot%202016-08-30%20at%209.39.02%20AM.png

Oddly, when I access the same notebook (Winows10, Chrome), I do see the notebook: 
![image](https://cloud.githubusercontent.com/assets/13372164/18095216/d7efb22a-6e9b-11e6-9b76-260b2d0d0cbb.png)

**Comment by rafaelhbarros** [comment]
Shows like this for me: <img width="1079" alt="screen shot 2016-08-30 at 9 39 02 am" src="https://cloud.githubusercontent.com/assets/3138550/18095498/cb19696e-6e9c-11e6-99dc-cb5f58f3182f.png">

OSX, Chrome.

**Comment by dsludwig** [comment]
This issue should be resolved.
