### ISSUE TITLE
Cloud upload

### ISSUE THREAD

**Issue by mlettau** [Anaconda-Platform/support#69]
When I try to upload a notebook to Anaconda cloud, I get the following error message when I click on the jupyter UI button:

Error: Not Found
An error ocurred in the Notebook Server

**Comment by koverholt** [comment]
Closing this as stale. The notebook extensions such as this one (https://github.com/Anaconda-Platform/nb_anacondacloud/issues) no longer ship by default in the Anaconda Distribution.
