### ISSUE TITLE
Anaconda Cloud: Version badge not always refreshing on new version upload

### ISSUE THREAD

**Issue by jakirkham** [Anaconda-Platform/support#7]
When adding a new version of a package to Anaconda Cloud, the version badge does not always get regenerated. As a results, badges often lag a version or two behind the actual version. It would be nice to fix this. It might also be nice to have a button to force a refresh of the version badge if it is out of date.

**Comment by srossross** [comment]
@jakirkham thanks for the update, we are looking into this now.

**Comment by stephenakearns** [comment]
See also potentially related issue Anaconda-server/anaconda-server#314

**Comment by rafaelhbarros** [comment]
With new changes on the metadata this will become easier to fix, currently I'm having a hard time reproducing.

**Comment by jakirkham** [comment]
Here's a reproducer ( https://anaconda.org/nanshe/nanshe/badges ).

**Comment by stephenakearns** [comment]
To confirm the specifics, I think you are pointing to the fact that the
badge is showing latest version as 0.1.0a39 but there are two newer
versions (.40 and .41). Am I understanding correctly?

On Tue, Jan 5, 2016 at 8:10 AM, jakirkham <notifications@github.com> wrote:

> Here's a reproducer ( https://anaconda.org/nanshe/nanshe/badges ).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Anaconda-Server/support/issues/7#issuecomment-169010652>
> .
>



-- 
*Stephen Kearns*
*Product Manager*

*w: (512) 776-1096*
*m: (737) 444-0474*
*t: @stephenakearns*
*skype: stephen.kearns*

**Comment by jakirkham** [comment]
Correct.

**Comment by Horta** [comment]
I'm having exactly the same problem: https://github.com/PMBio/limix

**Comment by jakirkham** [comment]
Also seeing this with `conda-smithy`. It shows 2.0.1 on the badge, but 2.2.1 is rolling out. Screenshots below. This has been out of date for a while.

This happens with other conda-forge packages as well. Packagers, who are often developers of their package, pick up on it and often gripe to us as this [comment]( https://github.com/conda-forge/tqdm-feedstock/pull/9#issuecomment-264642663 ) demonstrates. While I understand this is not a big ticket item, it doesn't look great for either of us when the badges are out-of-date. Would be nice if someone looked into it. 😄

<img width="1552" alt="screen shot 2017-03-23 at 00 02 38" src="https://cloud.githubusercontent.com/assets/3019665/24231635/234b105a-0f5c-11e7-96c1-9081adaa4980.png">

<img width="1552" alt="screen shot 2017-03-23 at 00 02 03" src="https://cloud.githubusercontent.com/assets/3019665/24231636/234c8a52-0f5c-11e7-83a4-0ce8c17a1811.png">

**Comment by jakirkham** [comment]
Thank you. ❤️

**Comment by rolando** [comment]
Is this issue https://github.com/ContinuumIO/anaconda-issues/issues/1584#issuecomment-291940231 the same case?

**Comment by csoja** [comment]
@abarto which version of Anaconda Cloud has/will have the fix for outdated badges?

**Comment by abarto** [comment]
@csoja 2.28.1. It hasn't been deployed yet.

**Comment by abarto** [comment]
@rolando Yes, I think it is related.

**Comment by rolando** [comment]
@abarto Good, thanks for the reply!
