### ISSUE TITLE
Kapsel deploy problems

### ISSUE THREAD

**Issue by ijstokes** [Anaconda-Platform/support#70]
I just deployed my first Kapsel. I don't know what happened but it didn't work so far as I can tell.

I have this entry:

<img width="1132" alt="screen shot 2016-09-06 at 4 01 08 pm" src="https://cloud.githubusercontent.com/assets/293525/18288930/495dbe34-744b-11e6-8e84-c8381c43b019.png">

And for one it has totally the wrong timestamp: I created that minutes ago, not a week ago (off-by-a-week error?)

But I already clicked "Deploy" and put in my AWS creds.  Nothing happened.  How do I access the thing I created?  How do I go back and find my created Kapsels from http://anaconda.org/ijstokes?  Oh, I tried adding `/kapsels` to the end of the URL.  Surely there is a better way to do this, but I can't find it.

And now on my second attempt to deploy something through Anaconda Cloud and with Kapsel I am met with a different (and more explicit, though the cause is not clear) failure.  For anyone who can access it, here is a screencast:

http://filer.corp.continuum.io/~ijstokes/2016-09-06_1610.swf

Other notes:
- I entered a summary, I'd swear, but nothing appeared in the Kapsel def.

**Comment by koverholt** [comment]
Closing this as stale / deprecated functionality of Anaconda Cloud.
