### ISSUE TITLE
Links don't seem to work reasonably from within Jupyter notebooks

### ISSUE THREAD

**Issue by jbednar** [Anaconda-Platform/support#72]
I just uploaded a notebook to https://anaconda.org/jbednar/paramnb/notebook, and links in markdown cells  list the correct target (as can be seen when hovering over them), but they don't work as I had been expecting:

The third link in the notebook (to ipywidgets) renders inside the anaconda.org frame, which doesn't seem appropriate -- that's a link to an external site, and surely should be a fresh new browser page?  (Either in the same tab, or in a new tab (your choice!), but not inside the frame that previously contained the notebook, right?)

Presumably using the frame in that way is what's causing a more serious issue, which is that the first two links on the page, both of which go to github, don't display anything at all (the links labeled ParamNB and Param Library). 

Can this behavior be changed?

**Comment by dsludwig** [comment]
This was fixed in the latest release of Anaconda Cloud 2.20.4. Thanks!
