### ISSUE TITLE
Missing 38 packages from index

### ISSUE THREAD

**Issue by jakirkham** [Anaconda-Platform/support#73]
It appears that there are 38 packages that are simply not in the conda-forge index. Please see this [comment]( https://github.com/conda-forge/conda-forge.github.io/issues/171#issuecomment-247251636 ) for details. This value was determined by looking at the number of packages reported by anaconda.org and the number found in the index file.

cc @msarahan @jjhelmus @pelson @patricksnape

**Comment by jjhelmus** [comment]
This is caused by the script in question only examining packages for the platform on which the script was run.  This is not an issue with Anaconda.org

**Comment by jakirkham** [comment]
Ok, thanks for clarifying, @jjhelmus. Sorry for the noise everyone. Closing this out.
