### ISSUE TITLE
Missing entry info for 26 packages

### ISSUE THREAD

**Issue by jakirkham** [Anaconda-Platform/support#74]
It appears there are 26 packages in the index that we are unable to find a download link or any other relevant info for. This could be a bug on our end or not. It is unclear.

Relevant info including the script used can be found in this [comment]( https://github.com/conda-forge/conda-forge.github.io/issues/171#issuecomment-247251636 ). The package is determined to be missing entries if this [block of code]( https://gist.github.com/jakirkham/621cd3a03098205f5eba83533df932fe#file-binary_prefix_check_file-py-L62-L67 ) results in the package being skipped. This could mean there is a bug [here]( https://gist.github.com/jakirkham/621cd3a03098205f5eba83533df932fe#file-binary_prefix_check_file-py-L19-L26 ) if there is one.

cc @msarahan @jjhelmus @patricksnape @pelson

**Comment by jjhelmus** [comment]
This is a bug in the script used to find the latest versions of the packages and filtering out all non-latest versions.  If the package uses a non-standard version scheme or uses post released all instances of the package can be filtered out.

**Comment by jakirkham** [comment]
Ok, thanks for that clarification. Sorry again for the noise. Closing...
