### ISSUE TITLE
Supporting msys2 on all platforms

### ISSUE THREAD

**Issue by jakirkham** [Anaconda-Platform/support#76]
**Please read what follows carefully.**

Re-rendering with [`conda-smithy`](https://github.com/conda-forge/conda-smithy) currently cannot be done on Windows. This boils down to the fact that we must masquerade as a different OS than the one we are on currently. Combining this with how `conda` behaves it results in checking channels like the ones listed below. A much longer explanation is given in this [comment](https://github.com/conda-forge/conda-smithy/issues/281#issuecomment-252806009).

Even though we all know there are no packages from [`msys2`](https://repo.continuum.io/pkgs/msys2/) for anything other than Windows, it would be really helpful to have `msys2` behave a bit more like [`free`](https://repo.continuum.io/pkgs/free/) or [`pro`](https://repo.continuum.io/pkgs/pro/). It appears that [`noarch` on `msys2`](https://repo.continuum.io/pkgs/msys2/noarch/) already is a stub. It would be really helpful to have these URLs as stubs too.
- https://repo.continuum.io/pkgs/msys2/osx-64/
- https://repo.continuum.io/pkgs/msys2/linux-64/
- https://repo.continuum.io/pkgs/msys2/osx-32/
- https://repo.continuum.io/pkgs/msys2/linux-32/

cc @msarahan @mcg1969 @kalefranz @mingwandroid @Korijn @ivoflipse @ocefpaf @pelson

**Comment by jakirkham** [comment]
Any thoughts on this? I would hope this is an easy, sensible fix. Though maybe I'm wrong. Would be great to hear from someone either way. :smile:

**Comment by Korijn** [comment]
I'd love to see a fix for this as well, but I'm unaware of a method for me to contribute such a PR. Is this even an open source project?

**Comment by ccordoba12** [comment]
Pinging @mingwandroid about this one

**Comment by kalefranz** [comment]
Actually, there's something more fundamental here.  Conda right now ignores 404s for `/noarch/repodata.json`, but insists on having `/PLATFORM/repodata.json` for any listed channel.  That's because conda needs a way to make sure you haven't fat-fingered a channel url.

I think we should probably flip this paradigm.  For a channel to be valid, it must have a `/noarch/repodata.json` file.  And then other platforms are optional.

Thoughts?

**Comment by kalefranz** [comment]
We should probably move this issue to the conda issue tracker if it heads in the direction I've proposed.

**Comment by jakirkham** [comment]
Yep, I'm completely ok with your proposal @kalefranz . I guess I'm trying to find the balance between getting something working now and getting something working in a few weeks.

Should note that part of the motivation is Travis CI switched their default image and are bumping their lower end image at the end of the month. This puts us on a time table where we need as many people able to run re-renderings with `conda-smithy` as possible.

xref: https://github.com/conda-forge/conda-forge.github.io/issues/249

**Comment by jakirkham** [comment]
Any chance we can get the simple fix for the msys2 channel in the near term? Is this easy enough to do @mingwandroid ?

**Comment by mingwandroid** [comment]
Because the msys2 channel syncs from anaconda.org it's probably not as easy as running conda index in an empty folder. I'll discuss it later though.

**Comment by ocefpaf** [comment]
IMO the issue is in `conda-smithy` making a bad assumption that all platforms should be equal regarding the available channels. It should not be hard to fix it there.

**Comment by jakirkham** [comment]
> Because the msys2 channel syncs from anaconda.org it's probably not as easy as running conda index in an empty folder. I'll discuss it later though.

Given this, I agree we should take this up as an issue in `conda` as suggested by @kalefranz . I'm replacing this with issue ( https://github.com/conda/conda/issues/3933 ). Feel free to continue the discussion there.
