### ISSUE TITLE
Spyder and Navigator do not launch.

### ISSUE THREAD

**Issue by monarchid** [Anaconda-Platform/support#79]
Hello -

I have installed Anaconda2 x64  (Python 2.7.12 |Anaconda 4.2.0 (64-bit)| (default, Jun 29 2016, 11:07:13) [MSC v.1500 64 bit (AMD64)]).  Neither Spyder nor Navigator launch from the program list.  It appears that pythonw is opening and closing immediately.  

Any advice or suggestion would be greatly appreciated.

Thank you.

David

**Comment by mingwandroid** [comment]
In this situation I would investigate with procmon.

**Comment by monarchid** [comment]
Thank you for the suggestion, Ray.  I monitored the execution with ProcMan as you suggested.  However, I don’t see anything to point me to the problem except  possibly the Exit Status 1 shown near the end of the attached file.  Unfortunately I am not able to interpret the output.  I would be grateful is you would take a look at it to see if you can identify the problem.

Thank you.

David
[Logfile.zip](https://github.com/Anaconda-Platform/support/files/529937/Logfile.zip)

**Comment by koverholt** [comment]
Closing as stale. Issues with the Anaconda Distribution can be reported at https://github.com/continuumio/anaconda-issues/issues.
