### ISSUE TITLE
Default file sort

### ISSUE THREAD

**Issue by jakirkham** [Anaconda-Platform/support#80]
The default package file sort use to be the same as a sort by most recent ( `?sort=time&sort_order=desc` ). However, that appears to no longer be the case.

<img width="1554" alt="screen shot 2016-10-19 at 0 31 10" src="https://cloud.githubusercontent.com/assets/3019665/19505735/62f8e184-9593-11e6-91f5-a5aed12b81d8.png">

**Comment by csoja** [comment]
Thanks for the report.  A fix for this is included in the upcoming release.

**Comment by j0hn** [comment]
Closing since it's already fixed.
