### ISSUE TITLE
anaconda copy between channels leaves destination copy in an inconsistent state

### ISSUE THREAD

**Issue by mj-harvey** [Anaconda-Platform/support#83]
Hi,

I'm trying to copy a package from the omnia channel using command:

> anaconda copy --to-owner acellera omnia/ambermini/15.0.4

The command succeeds, in the process creating the package acellera/ambermini, but a subsequent attempt to install fails:

> $ conda install ambermini
> Fetching package metadata .........
> Solving package specifications: .
> 
> 
> PackageNotFoundError: Package not found: '' Package missing in current linux-64 channels: 
>   - ambermini
> 
> You can search for packages on anaconda.org with
> 
>     anaconda search -t conda ambermini
> 

(yes, the channel is configured)

"anaconda show" gives:

> $ anaconda show acellera/ambermini/
> Using Anaconda Cloud api site https://api.anaconda.org
> Name:    ambermini
> Summary: A stripped-down set of just antechamber, sqm, and tleap.  See https://github.com/swails/ambermini
> Access:  public
> Package Types:  
> Versions:
>    + 14
>    + 14.0.1
>    + 15.0.3
>    + 15.0.4
>    + 16.16.0

Note the available versions aren't consistent with what's been copied, and the "Package types:" doesn't show "conda", as for packages I have manually uploaded.

The web landing page:
[https://anaconda.org/acellera/ambermini/]
says no files are uploaded, but the files page
[https://anaconda.org/acellera/ambermini/files](url)
shows  the version 15.0.4 files  (not the other versions as listed in "anaconda show")

**Comment by csoja** [comment]
A fix for this will be included in the next release.

**Comment by dsludwig** [comment]
@mj-harvey thank you for reporting this issue. The command `anaconda show acellera/ambermini` now shows the correct versions:

```
Name:    ambermini
Summary: A stripped-down set of just antechamber, sqm, and tleap.  See https://github.com/swails/ambermini
Access:  public
Package Types:  conda
Versions:
   + 14.0.1
   + 15.0.4
   + 16.16.0
```

Please re-open this issue if you run into this problem again, or create a new issue. Thanks!

**Comment by mj-harvey** [comment]
Thanks for the update. I'll have to confirm that the "anaconda copy" actually works now though, as I manually synced the ambermini package myself.
