### ISSUE TITLE
Where does one update their profile picture?

### ISSUE THREAD

**Issue by jakirkham** [Anaconda-Platform/support#84]
@pelson commented on [Wed Feb 10 2016](https://github.com/Anaconda-Platform/docs.anaconda.org/issues/252)

The UI seems to have changed recently on anaconda.org, and I'm embarrassed to say I can't find a way to change my profile picture. Any advice?

Thanks!

---

@ostrokach commented on [Sun Jul 24 2016](https://github.com/Anaconda-Platform/docs.anaconda.org/issues/252#issuecomment-234760864)

Any update on this? Or are profile pictures not supported yet?

---

@jakirkham commented on [Sun Nov 06 2016](https://github.com/Anaconda-Platform/docs.anaconda.org/issues/252#issuecomment-258703505)

Any thoughts on this? I'm also clueless as to how to change this setting.

---

Copied from issue ( https://github.com/Anaconda-Platform/docs.anaconda.org/issues/252 ).

**Comment by csoja** [comment]
Anaconda Cloud displays your profile photo if the email address you used to register on Anaconda Cloud is associated with a Gravatar account. Go to gravatar.com to associate your email address or to change your Gravatar profile photo.

This information can be found on this page: https://docs.continuum.io/anaconda-cloud/managing-account - but it is not easy to find.  This is also not clear in the UI - and it is definitely something that could be improved.

**Comment by pelson** [comment]
Thanks @csoja. Do you know how this works for organisations?

Thanks!

**Comment by csoja** [comment]
Should be the same way - using the default email address of the organization.

**Comment by jakirkham** [comment]
Maybe you could setup a GMail alias @pelson using the [`+` trick]( http://fieldguide.gizmodo.com/how-to-use-the-infinite-number-of-email-addresses-gmail-1609458192 ).

**Comment by pelson** [comment]
Thanks @csoja & @jakirkham. I'd say this was good to close, although it might be nice to have a link to the gravatar site when we are in the "edit profile" screen.

**Comment by csoja** [comment]
I will close this issue. However, I added an internal issue with the helpful suggestion for that "edit profile" screen - so we won't loose track of it.
