### ISSUE TITLE
HTTPError 409 Client Error - Conflict for url ?

### ISSUE THREAD

**Issue by jakirkham** [Anaconda-Platform/support#85]
Sometimes am seeing a 409 HTTPError. The error message looks like the one below. This appears to be transient as it often goes away on restart.

```
HTTPError: 409 Client Error: Conflict for url: https://repo.continuum.io/pkgs/free/linux-64/repodata.json.bz2: https://repo.continuum.io/pkgs/free/linux-64/
```

**Comment by csoja** [comment]
@jakirkham are you still seeing this issue?

**Comment by koverholt** [comment]
Closing as stale. In the future, bugs or enhancement requests for Anaconda Cloud can be submitted at https://www.anaconda.com/contact-us/ if this issue occurs again.
