### ISSUE TITLE
installing conda-forge tensorflow

### ISSUE THREAD

**Issue by kalefranz** [Anaconda-Platform/support#87]
_From @Estifo on November 20, 2016 8:7_

Could not connect to https://conda.anaconda.org/conda-forge/linux-64/
Could not connect to https://conda.anaconda.org/conda-forge/noarch/
Could not connect to https://conda.anaconda.org/conda-forge/linux-64/
An unexpected error has occurred.
 how can i fix this ???

_Copied from original issue: conda/conda#3920_

**Comment by kalefranz** [comment]
_From @soapy1 on November 21, 2016 16:14_

Does this happen consistently e.g. did you try to install again a little bit later?
Also, could you provided the output to `conda info`

**Comment by koverholt** [comment]
Closing as stale. In the future, bugs or enhancement requests for Anaconda Cloud can be submitted at https://www.anaconda.com/contact-us/ if this issue occurs again.
