### ISSUE TITLE
Missing libgcc

### ISSUE THREAD

**Issue by bloodymeli** [Anaconda-Platform/support#88]
It appears there's an issue with anaconda.org and the libgcc-5 package on the ostrokach channel. The stack trace indicates you got a 404 NOT FOUND error for the URL

https://conda.anaconda.org/ostrokach/linux-64/libgcc-5-5.4.0-2.tar.bz2
that anaconda.org indicated existed in https://conda.anaconda.org/ostrokach/linux-64/repodata.json.

See also [here](http://askubuntu.com/questions/853016/conda-apt-get-issues-installing-graph-tool).

**Comment by koverholt** [comment]
Closing as stale. In the future, bugs or enhancement requests for Anaconda Cloud can be submitted at https://www.anaconda.com/contact-us/ if this issue occurs again.
