### ISSUE TITLE
License link

### ISSUE THREAD

**Issue by jakirkham** [Anaconda-Platform/support#89]
It seems that the license link in the Anaconda.org UI tries to come up with a link to OSI. However, not everything that goes in the `license` field of `meta.yaml` will yield a reasonable link. For example, please take a look at the image below. It would be nice if we could come up with a better way to handle license links. Some options that I can think of below. Other suggestions welcome.

* Link to the license file in the package (fallback to OSI if not provided).
* Provide new metadata in `meta.yaml` to override the license link.

<img width="1554" alt="screen shot 2016-11-29 at 12 27 14" src="https://cloud.githubusercontent.com/assets/3019665/20720983/43d88c98-b62f-11e6-9907-11f60df71ce2.png">

**Comment by jakirkham** [comment]
Maybe a reasonable fix would be to allow the license file included in the package (assuming there is one) to be viewed and/or downloaded from the Web UI.

**Comment by koverholt** [comment]
Issue moved to [Anaconda-Platform/anaconda-server #4791](https://github.com/Anaconda-Platform/anaconda-server/issues/4791) via [**ZenHub**](https://www.zenhub.com/)
