### ISSUE TITLE
Python Auto Completion doesn't always work

### ISSUE THREAD

**Issue by kspanakis** [Anaconda-Platform/support#90]
Hello. I installed conda opencv-2.4.11 in Anaconda but autocompletion doesn't work at all, while it does for other packages. What could be the problem?

**Comment by koverholt** [comment]
This does not appear to be an issue with Anaconda Cloud. Issues related to Anaconda or Conda can be reported in the corresponding Github issue tracker: https://anaconda.org/contact/report.
