### ISSUE TITLE
Badge version doesn't match package version

### ISSUE THREAD

**Issue by pmlandwehr** [Anaconda-Platform/support#92]
Hey-lo,

We're having a running issue with the version badges for [conda-forge's `tqdm` package](https://anaconda.org/conda-forge/tqdm). As you can see, the build version is `4.11.1`. However, the [badge](https://anaconda.org/conda-forge/tqdm/badges) says that the Anaconda Cloud version is only `4.9`. Any idea how we can fix this?

**Comment by casperdcl** [comment]
might want to rename this issue title cersion->version ;)

**Comment by j0hn** [comment]
Looks like its already fixed
