### ISSUE TITLE
libtiff

### ISSUE THREAD

**Issue by pauldebeurs** [Anaconda-Platform/support#94]
Anaconda Navigator shows: libtiff version 4.0.6 installed
=================
Spider shows:
Python 3.5.2 |Anaconda 4.2.0 (x86_64)| (default, Jul  2 2016, 17:52:12)
Type "copyright", "credits" or "license" for more information.

IPython 5.1.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

import libtiff
Traceback (most recent call last):

  File "<ipython-input-1-4492fa448634>", line 1, in <module>
    import libtiff

ImportError: No module named 'libtiff'
=================
So I think libtiff is not a correct Python module.
I found this: libtiff - a wrapper of C libtiff library using ctypes.
What do I need to read tiff-files?

**Comment by koverholt** [comment]
This does not appear to be an issue with Anaconda Cloud. Issues related to Anaconda or Conda can be reported in the corresponding Github issue tracker: https://anaconda.org/contact/report.
