### ISSUE TITLE
Anaconda-Navigator Crashes In Launch Process OS X Sierra 

### ISSUE THREAD

**Issue by kronos455** [Anaconda-Platform/support#96]
I have a MacBook Pro (late 2013) with OS X Sierra 10.12.3, 2GHz i7, & 16 GB RAM. 

When I launch Anaconda3 4.3.0, it will crash in the process. I had to revert back to Anaconda3 4.1.1. I've sent numerous crash reports via the Apple reporting system.

Anaconda3 4.1.1 seems to work fine but I cannot add applications without causing Anaconda to update itself and then crash the next time I start up.

**Comment by goanpeca** [comment]
@kronos455 run 

`sudo rm -rf ~/.continuum/` on the terminal and run the latest version of navigaot

**Comment by kronos455** [comment]
This worked. Thanks!

**Comment by koverholt** [comment]
This does not appear to be an issue with Anaconda Cloud. Issues related to Anaconda or Conda can be reported in the corresponding Github issue tracker: https://anaconda.org/contact/report.
